name: Java CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: run tests
      run: ./gradlew test
    - name: upload test report
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test report
        path: build/reports/tests/test
    - name: make report
      if: always()
      run: ./gradlew codeCoverageReport
    - name: upload coverage report
      uses: actions/upload-artifact@v1.0.0
      with:
        name: coverage report
        path: build/reports/jacoco/codeCoverageReport/html
    - name: code coverage
      run: ./gradlew testCodeCoverage
